// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Ingredient struct {
	ID   int32       `json:"id"`
	Name pgtype.Text `json:"name"`
}

type Recipe struct {
	ID         int32       `json:"id"`
	Name       pgtype.Text `json:"name"`
	Synopsis   pgtype.Text `json:"synopsis"`
	Time       pgtype.Int4 `json:"time"`
	Difficulty pgtype.Int4 `json:"difficulty"`
}

type RecipesIngredient struct {
	RecipeID     pgtype.Int4 `json:"recipe_id"`
	IngredientID pgtype.Int4 `json:"ingredient_id"`
	Amount       pgtype.Int4 `json:"amount"`
	Unit         pgtype.Int4 `json:"unit"`
}

type RecipesTag struct {
	RecipeID pgtype.Int4 `json:"recipe_id"`
	TagID    pgtype.Int4 `json:"tag_id"`
}

type Review struct {
	ID       int32       `json:"id"`
	RecipeID pgtype.Int4 `json:"recipe_id"`
	UserID   pgtype.Int4 `json:"user_id"`
	Review   pgtype.Int4 `json:"review"`
}

type Tag struct {
	ID     int32       `json:"id"`
	Name   pgtype.Text `json:"name"`
	TypeID pgtype.Int4 `json:"type_id"`
}

type TagsType struct {
	ID   int32       `json:"id"`
	Name pgtype.Text `json:"name"`
}

type User struct {
	ID        int32            `json:"id"`
	Username  pgtype.Text      `json:"username"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	Passwd    pgtype.Text      `json:"passwd"`
	Email     pgtype.Text      `json:"email"`
	Name      pgtype.Text      `json:"name"`
	Surname   pgtype.Text      `json:"surname"`
	Phone     pgtype.Int4      `json:"phone"`
	Age       pgtype.Int4      `json:"age"`
	Sex       pgtype.Bool      `json:"sex"`
	Weight    pgtype.Int4      `json:"weight"`
	Height    pgtype.Int4      `json:"height"`
	Bmi       pgtype.Int4      `json:"bmi"`
}
