// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, passwd, email, sex, age)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, passwd, email, sex, age
`

type CreateUserParams struct {
	Username pgtype.Text `json:"username"`
	Passwd   pgtype.Text `json:"passwd"`
	Email    pgtype.Text `json:"email"`
	Sex      pgtype.Bool `json:"sex"`
	Age      pgtype.Int4 `json:"age"`
}

type CreateUserRow struct {
	ID       int32       `json:"id"`
	Username pgtype.Text `json:"username"`
	Passwd   pgtype.Text `json:"passwd"`
	Email    pgtype.Text `json:"email"`
	Sex      pgtype.Bool `json:"sex"`
	Age      pgtype.Int4 `json:"age"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Passwd,
		arg.Email,
		arg.Sex,
		arg.Age,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Passwd,
		&i.Email,
		&i.Sex,
		&i.Age,
	)
	return i, err
}
